name: docker build

on: [push]

jobs:
  docker-agw-gateway-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build and push
        run: |
          # Clone magma repo with ARM AGW Dockerfile
          git clone https://github.com/m-govind/magma.git --depth 1
          export MAGMA_ROOT=${PWD}/magma
          cd ${MAGMA_ROOT}/lte/gateway/docker/services/

          # Update artifactory gpg public key URL
          sed -i 's,https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/ShubhamTatvamasi/magma-artifactory-gpg/master/public,g' python/Dockerfile

          # Update docker platform
          sed -i 's,FROM,FROM --platform=linux/arm64,g' python/Dockerfile

          # update CPU_ARCH
          sed -i 's,x86_64,aarch64,g' python/Dockerfile

          # update DEB_PORT
          sed -i 's,amd64,arm64,g' python/Dockerfile

          cd ${MAGMA_ROOT}

          yq e '.services.gateway_python.build.x-bake.tags = "shubhamtatvamasi/agw_gateway_python"' -i lte/gateway/docker/docker-compose.override.yaml

          docker buildx bake --push -f lte/gateway/docker/docker-compose.override.yaml gateway_python

  docker-agw-gateway-c:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build and push
        run: |
          # Clone magma repo with ARM AGW Dockerfile
          git clone https://github.com/m-govind/magma.git --depth 1
          export MAGMA_ROOT=${PWD}/magma
          cd ${MAGMA_ROOT}/lte/gateway/docker/services/

          # Update artifactory gpg public key URL
          sed -i 's,https://artifactory.magmacore.org/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/ShubhamTatvamasi/magma-artifactory-gpg/master/public,g' c/Dockerfile
          sed -i 's,https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/ShubhamTatvamasi/magma-artifactory-gpg/master/public,g' c/Dockerfile

          # Update docker platform
          sed -i 's,FROM,FROM --platform=linux/arm64,g' c/Dockerfile

          # update CPU_ARCH
          sed -i 's,x86_64,aarch64,g' c/Dockerfile

          # update DEB_PORT
          sed -i 's,amd64,arm64,g' c/Dockerfile

          cd ${MAGMA_ROOT}

          yq e '.services.gateway_c.build.x-bake.tags = "shubhamtatvamasi/agw_gateway_c"' -i lte/gateway/docker/docker-compose.override.yaml

          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

          docker buildx bake --push -f lte/gateway/docker/docker-compose.override.yaml gateway_c
