name: docker build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build
        run: |
          # Clone magma repo with ARM AGW Dockerfile
          git clone https://github.com/m-govind/magma.git --depth 1
          cd magma/lte/gateway/docker/

          # Update artifactory gpg public key URL
          sed -i 's,https://artifactory.magmacore.org/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/TatvamasiLabs/gpg/main/public,g' services/c/Dockerfile
          sed -i 's,https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/TatvamasiLabs/gpg/main/public,g' services/c/Dockerfile
          sed -i 's,https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/TatvamasiLabs/gpg/main/public,g' services/python/Dockerfile

          # Add ARM Platform for building docker images
          yq e '.services.gateway_c.platform = "linux/arm64"' -i docker-compose.override.yaml
          yq e '.services.gateway_python.platform = "linux/arm64"' -i docker-compose.override.yaml

          # Build docker images
          docker-compose build --build-arg CPU_ARCH=aarch64 --build-arg DEB_PORT=arm64 gateway_python

      - name: Docker Push
        run: |
          # docker tag agw_gateway_c shubhamtatvamasi/agw_gateway_c
          # docker push shubhamtatvamasi/agw_gateway_c

          docker tag agw_gateway_python shubhamtatvamasi/agw_gateway_python
          docker push shubhamtatvamasi/agw_gateway_python
