name: docker build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build
        run: |
          git clone https://github.com/TatvamasiLabs/magma.git
          cd magma/lte/gateway/docker/

          # yq e '.services.gateway_c.platform = "linux/arm64"' -i docker-compose.override.yaml
          # yq e '.services.gateway_python.platform = "linux/arm64"' -i docker-compose.override.yaml

          # docker-compose build --build-arg CPU_ARCH=aarch64 --build-arg DEB_PORT=arm64

          docker-compose build

      - name: Docker Push
        run: |
          docker tag agw_gateway_python shubhamtatvamasi/agw_gateway_python
          docker tag agw_gateway_c shubhamtatvamasi/agw_gateway_c

          docker push shubhamtatvamasi/agw_gateway_python
          docker push shubhamtatvamasi/agw_gateway_c
