name: docker build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build
        run: |
          # git clone https://github.com/TatvamasiLabs/magma.git --depth 1
          git clone https://github.com/m-govind/magma.git --depth 1
          cd magma/lte/gateway/docker/

          sed -i 's,https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/TatvamasiLabs/gpg/main/public,g' services/c/Dockerfile

          # sed -i 's,https://artifactory.magmacore.org/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/TatvamasiLabs/gpg/main/public,g' services/c/Dockerfile

          # services/c/Dockerfile
          # services/python/Dockerfile

          yq e '.services.gateway_c.platform = "linux/arm64/v8"' -i docker-compose.override.yaml
          yq e '.services.gateway_python.platform = "linux/arm64/v8"' -i docker-compose.override.yaml

          export DOCKER_BUILDKIT=1

          mv docker-compose.yaml docker-compose.yaml.bak
          mv docker-compose.override.yaml docker-compose.yaml

          docker-compose build --build-arg CPU_ARCH=aarch64 --build-arg DEB_PORT=arm64 gateway_c

          # docker-compose build

      - name: Docker Push
        run: |
          # docker tag agw_gateway_python shubhamtatvamasi/agw_gateway_python
          docker tag agw_gateway_c shubhamtatvamasi/agw_gateway_c

          # docker push shubhamtatvamasi/agw_gateway_python
          docker push shubhamtatvamasi/agw_gateway_c
