name: docker build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: install latest docker-compose
        run: |
          export LATEST_VERSION=$(curl -s https://github.com/docker/compose/releases/latest | grep -o "v[0-9]\.[0-9]*\.[0-9]*")
          sudo curl -L "https://github.com/docker/compose/releases/download/$LATEST_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Docker build
        run: |
          # Clone magma repo with ARM AGW Dockerfile
          git clone https://github.com/m-govind/magma.git --depth 1
          export MAGMA_ROOT=${PWD}/magma
          cd ${MAGMA_ROOT}/lte/gateway/docker/

          # Update artifactory gpg public key URL
          sed -i 's,https://artifactory.magmacore.org/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/ShubhamTatvamasi/magma-artifactory-gpg/master/public,g' services/c/Dockerfile
          sed -i 's,https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/ShubhamTatvamasi/magma-artifactory-gpg/master/public,g' services/c/Dockerfile
          sed -i 's,https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public,https://raw.githubusercontent.com/ShubhamTatvamasi/magma-artifactory-gpg/master/public,g' services/python/Dockerfile

          # Update docker platform
          sed -i 's,FROM,FROM --platform=linux/arm64,g' services/c/Dockerfile
          sed -i 's,FROM,FROM --platform=linux/arm64,g' services/python/Dockerfile

          # update CPU_ARCH
          sed -i 's,x86_64,aarch64,g' services/c/Dockerfile
          sed -i 's,x86_64,aarch64,g' services/python/Dockerfile

          # update DEB_PORT
          sed -i 's,amd64,arm64,g' services/c/Dockerfile
          sed -i 's,amd64,arm64,g' services/python/Dockerfile

          yq e '.services.gateway_c.platform = "linux/arm64/v8"' -i docker-compose.override.yaml
          yq e '.services.gateway_python.platform = "linux/arm64/v8"' -i docker-compose.override.yaml

          # Build docker images
          docker-compose build

      - name: Docker Push
        run: |
          docker tag agw_gateway_c shubhamtatvamasi/agw_gateway_c
          docker push shubhamtatvamasi/agw_gateway_c

          docker tag agw_gateway_python shubhamtatvamasi/agw_gateway_python
          docker push shubhamtatvamasi/agw_gateway_python
