name: docker build

on: [push]

jobs:
  docker-build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Clone Magma repo
        run: git clone https://github.com/m-govind/magma.git

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          context: magma/lte/gateway/docker/services/python
          push: true
          tags: shubhamtatvamasi/agw_gateway_python:latest

  docker-build-c:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Clone Magma repo
        run: git clone https://github.com/m-govind/magma.git

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          context: magma/lte/gateway/docker/services/c
          push: true
          tags: shubhamtatvamasi/agw_gateway_c:latest



      # - name: Test
      #   run: |
      #     docker buildx ls


      #     docker-compose build --build-arg CPU_ARCH=aarch64 --build-arg DEB_PORT=arm64

      # - name: Docker Push
      #   run: |
      #     docker tag agw_gateway_python shubhamtatvamasi/agw_gateway_python
      #     docker tag agw_gateway_c shubhamtatvamasi/agw_gateway_c

      #     docker push shubhamtatvamasi/agw_gateway_python
      #     docker push shubhamtatvamasi/agw_gateway_c
